
global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
scrape_configs:
  - job_name: "Linux-Server"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "process-exporter"
    static_configs:
      - targets: ["process_exporter:9256"]
